In [ ]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

## Quantum Objects

In [17]:
Qobj([[1],[2],[3],[4],[5]])

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]

In [3]:
basis(5,3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [4]:
coherent(5,0.5-0.5j)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.7788017 +0.j        ]
 [ 0.38939142-0.38939142j]
 [ 0.        -0.27545895j]
 [-0.07898617-0.07898617j]
 [-0.04314271+0.j        ]]

In [5]:
destroy(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [6]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [7]:
jmat(5/2.0,'+')

Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[0.         2.23606798 0.         0.         0.         0.        ]
 [0.         0.         2.82842712 0.         0.         0.        ]
 [0.         0.         0.         3.         0.         0.        ]
 [0.         0.         0.         0.         2.82842712 0.        ]
 [0.         0.         0.         0.         0.         2.23606798]
 [0.         0.         0.         0.         0.         0.        ]]

In [8]:
q = destroy(4)
q.dims

(4, 4)

In [11]:
q.type

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

In [12]:
q.isherm

False

In [13]:
q.data

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

In [14]:
basis(5, 3).dag()

(4, 4)

In [15]:
coherent_dm(5, 1)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]

In [18]:
coherent_dm(5, 1).diag()

array([0.36791117, 0.36757705, 0.18523331, 0.05810197, 0.0211765 ])

## Manipulating States and Operators

In [19]:
vac = basis(5,0) #create a Fock vacuum state vector |0>
vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [23]:
a = destroy(5) #create a lowering operator corresponding to 5 number states
a

SyntaxError: invalid syntax (<ipython-input-23-60b471633396>, line 1)